### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by matmo1** [russhughes/st7789s3_mpy#10]
Hello, 
I'm new to programing MCUs. I'm bought t display s3 and use windows 10 and when I try to run the example code I get import error for st7789 module. I saw that there's a file named st7789.piy and I opened it tried to run it and it gave again import error that there's no module named typing. Also there isn't a file named typing in the example folder. What should I do?

**Comment by russhughes** [comment]
The pyi file is a stub file IDEs can use to provide autocomplete and help with syntax checking. It is not an executable file but a skeleton the of a Python module. Use the .py files or alternatively you can cross compile them using mpy-cross and use the resulting mpy file.
