### ISSUE TITLE
Bluetooth module is missing in precompiled firmware

### ISSUE THREAD

**Issue by j-denisb** [russhughes/st7789s3_mpy#2]
Any chance of updating firmware to include bluetooth?

Cheers.

**Comment by russhughes** [comment]
Yes, I've updated the firmware to MicroPython v1.19.1-896 with bluetooth.

**Comment by sylvain-lp** [comment]
I successfully tested firmware with Bluetooth yesterday, adding also the aioble module to facilitate operations. Was able to detect and display BLE devices around.Very much appreciate the quick improvement with this Bluetooth module included. SylvainOn Feb 27, 2023 06:57, Russ Hughes ***@***.***> wrote:
Yes, I've updated the firmware to MicroPython v1.19.1-896 with bluetooth.
