### ISSUE TITLE
lilygo t-hmi ST7789V

### ISSUE THREAD

**Issue by Valadimirovich** [russhughes/st7789s3_mpy#4]
Is there a way to make it work on lilygo t-hmi S3 board ?

**Comment by russhughes** [comment]
Not as it is now, it's some of it;s settings are specific to the T-Display-S3. The driver could be modified for the T-HMI but I'm working on another driver that will work on many S3 boards. It will work with SPI and Parallel interfaces. I expect to release in the next few days.
