### ISSUE TITLE
Examples Issue

### ISSUE THREAD

**Issue by enigma460** [russhughes/st7789s3_mpy#5]
Hi,
I have installed firmware v1.19.1-896 and tried to run some examples with no luck.

For example hello.py returns an error:
Traceback (most recent call last):
  File "<stdin>", line 12, in <module>
  File "tft_config.py", line 31, in config
TypeError: can't convert Pin to int

I also tried pinball.py and the screen turns blue and I need to use Ctrl-c to get prompt.

Any ideas to what I may be missing.

Thanks in advance

**Comment by russhughes** [comment]
Double-check that you are using the same version of the tft_config.py, tft_buttons.py, and firmware.bin.

**Comment by enigma460** [comment]
Ok I erased everything and started again. It now seems to work. May have mixed firmware.
Thanks for the fast supply.
