### ISSUE TITLE
Corrupted filesystem after uploading the firmware.

### ISSUE THREAD

**Issue by HabibMCS** [russhughes/st7789s3_mpy#7]
"The filesystem appears to be corrupted. If you had important data there, you
may want to make a flash snapshot to try to recover it. Otherwise, perform
factory reprogramming of MicroPython firmware (completely erase flash, followed
by firmware programming)."

I used the 16mb flash, with qio, in thonny at 408600 baud rate.  After pressing Ctrl+ C 
![error2](https://github.com/russhughes/st7789s3_mpy/assets/77892294/6e905fe7-aad0-422c-8da2-be912a9e6222)
the code runs but before it we get this issue.
![error_thonny](https://github.com/russhughes/st7789s3_mpy/assets/77892294/efd15f0e-fd20-49d6-9578-c00695acfe86)

**Comment by russhughes** [comment]
The size or location of the file partition may have changed. Erasing the flash and reflashing the MicroPython firmware should solve the problem.

**Comment by HabibMCS** [comment]
I am using thonny IDE for flashing the firmware. I erased and reflashed it several times. I have also tried "https://github.com/russhughes/st7789_mpy/tree/master/firmware/GENERIC_S3_7789"  flashing this one, it was not giving the error but the one in this repository is causing the issue.

 Also I am not able to save any file in the Micropython device. It says backend terminated.

**Comment by russhughes** [comment]
Could you check that Thonny is uploading the firmware to the correct starting address, 0x0 for the ESP32-S3, not the address 0x1000 used by the original ESP32 chip?

**Comment by HabibMCS** [comment]
It was detected automatically as 0x0, flash memory i used 16MB and in qio mode at baudrate 460800. I will check on same firmware on similar board and will check if it shows again or not  "https://github.com/Xinyuan-LilyGO/T-Display-S3" 
my display board is same as this one.

**Comment by russhughes** [comment]
That should work. I use T-Display-S3s all the time. I'll test one tonight.  Here is the driver I use for T-Display-S3s these days: https://github.com/russhughes/s3lcd

**Comment by HabibMCS** [comment]
![image](https://github.com/russhughes/st7789s3_mpy/assets/77892294/6a7ea9e3-9f83-4dc3-af25-82cc2a853cce)

can you mark which one I should write in my device , "https://github.com/Xinyuan-LilyGO/T-Display-S3"
i have this device provided in the link. " non touch version"

you can tell me the index number for corresponding firmware. Thanks for you replies and community service 🙏

**Comment by russhughes** [comment]
Use the S3LCD_OCT_16M firmware. See the README.md in the [firmware folder](https://github.com/russhughes/s3lcd/tree/main/firmware) for a list of 
 devices and which firmware to use.

**Comment by HabibMCS** [comment]
S3LCD_OCT_16M: Octal SPIRAM 16M Flash
I will try this one and will let you know
Thanks for your replies, 🙏

**Comment by HabibMCS** [comment]
same issue again 
![image](https://github.com/russhughes/st7789s3_mpy/assets/77892294/6d1ef3ad-e19c-4356-a512-18dd995a47dc)

**Comment by HabibMCS** [comment]
I ordered new one and tried to flash in it, it worked fine and there is no error in it. It was the hardware issue most probably. Thanks for your replies again🙏

**Comment by HabibMCS** [comment]
One more thing I figured out.  First I tried to flash arduino ide bootloader in it with wrong settings. It was flashed at wrong memory location. So when I tried to upload the micropython, previous bootloader was not erased properly. That caused an issue.
